# Generated by Django 5.2.4 on 2025-07-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwoWheelar',
            fields=[
                ('reg_no', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('bike_model', models.CharField(max_length=40)),
                ('purchase_date', models.DateField()),
                ('brand', models.CharField(max_length=20)),
                ('cost', models.FloatField()),
            ],
        ),
    ]
